/**
 * `robots.txt` composer (PRD §6.4).
 *
 * The single most common failure mode for new BlogKit installs is "AI
 * crawlers can't reach the content," so the default output explicitly
 * allow-lists every documented AI user agent across OpenAI, Anthropic,
 * Google, Perplexity, Apple, Common Crawl, ByteDance, Mistral, DeepSeek,
 * and Qwen. Ignore-by-default is the wrong stance for this product.
 *
 * Operators who want to disallow specific crawlers do so by passing
 * `allowedCrawlers` as an explicit list, or by adding a directive via
 * `extraDirectives`.
 */

export interface AiCrawler {
  userAgent: string;
  /** Operator name for documentation comments. */
  operator: string;
  /** Surface where the crawler operates: training | search | live-fetch. */
  surface: "training" | "search" | "live-fetch";
}

/**
 * Documented AI crawlers as of 2026-Q1. New entrants get appended here so
 * users pick them up by upgrading the package (PRD §14, risk 5).
 */
export const AI_CRAWLERS: readonly AiCrawler[] = [
  // OpenAI
  { userAgent: "GPTBot",            operator: "OpenAI",     surface: "training" },
  { userAgent: "OAI-SearchBot",     operator: "OpenAI",     surface: "search" },
  { userAgent: "ChatGPT-User",      operator: "OpenAI",     surface: "live-fetch" },
  // Anthropic
  { userAgent: "ClaudeBot",         operator: "Anthropic",  surface: "training" },
  { userAgent: "Claude-User",       operator: "Anthropic",  surface: "live-fetch" },
  { userAgent: "Claude-SearchBot",  operator: "Anthropic",  surface: "search" },
  // Google
  { userAgent: "Google-Extended",   operator: "Google",     surface: "training" },
  { userAgent: "Googlebot",         operator: "Google",     surface: "search" },
  // Perplexity
  { userAgent: "PerplexityBot",     operator: "Perplexity", surface: "search" },
  { userAgent: "Perplexity-User",   operator: "Perplexity", surface: "live-fetch" },
  // Apple
  { userAgent: "Applebot-Extended", operator: "Apple",      surface: "training" },
  // Common Crawl (ingested by most foundation-model training runs)
  { userAgent: "CCBot",             operator: "Common Crawl", surface: "training" },
  // ByteDance / Doubao
  { userAgent: "Bytespider",        operator: "ByteDance",  surface: "training" },
  // Open-weight model operators
  { userAgent: "MistralAI-User",    operator: "Mistral",    surface: "live-fetch" },
  { userAgent: "DeepSeekBot",       operator: "DeepSeek",   surface: "training" },
  { userAgent: "Qwenbot",           operator: "Qwen",       surface: "training" },
] as const;

export interface BuildRobotsOptions {
  /** Absolute site URL — required so we can emit a sitemap reference. */
  siteUrl: string;
  /**
   * `"all"` allows every documented AI crawler.
   * `"none"` disallows all of them (still allows generic search engines).
   * An array allows only the listed user agents.
   */
  allowedCrawlers?: "all" | "none" | readonly string[];
  /** Paths to disallow for every user agent (e.g. `/admin`). */
  disallowPaths?: readonly string[];
  /** Sitemap path on the site. Defaults to `/sitemap.xml`. */
  sitemapPath?: string;
  /** Extra raw lines appended verbatim. Use for one-off directives. */
  extraDirectives?: readonly string[];
  /** When true, emits a leading comment block listing the AI crawlers. */
  includeProvenanceComment?: boolean;
}

export function buildRobotsTxt(opts: BuildRobotsOptions): string {
  const sitemapPath = opts.sitemapPath ?? "/sitemap.xml";
  const disallows = opts.disallowPaths ?? ["/admin", "/api/mcp"];
  const allowed = resolveAllowed(opts.allowedCrawlers ?? "all");
  const lines: string[] = [];

  if (opts.includeProvenanceComment !== false) {
    lines.push(
      "# Generated by @blogkit/seo. AI crawler allow-list reflects PRD §6.4.",
      "# To change: edit blogkit.config.ts → ai.allowedCrawlers, then republish.",
      "",
    );
  }

  // Per-crawler explicit allow blocks make the policy unambiguous to
  // operators reading the file (and to humans auditing for AI access).
  for (const crawler of AI_CRAWLERS) {
    const allow = allowed.has(crawler.userAgent);
    lines.push(`# ${crawler.operator} — ${crawler.surface}`);
    lines.push(`User-agent: ${crawler.userAgent}`);
    if (allow) {
      lines.push("Allow: /");
      for (const path of disallows) lines.push(`Disallow: ${path}`);
    } else {
      lines.push("Disallow: /");
    }
    lines.push("");
  }

  // Catch-all for everyone else (regular search engines, archivers, etc.).
  lines.push("User-agent: *");
  lines.push("Allow: /");
  for (const path of disallows) lines.push(`Disallow: ${path}`);
  lines.push("");

  if (opts.extraDirectives) {
    for (const directive of opts.extraDirectives) lines.push(directive);
    lines.push("");
  }

  const sitemapAbsolute = `${opts.siteUrl.replace(/\/+$/, "")}${
    sitemapPath.startsWith("/") ? sitemapPath : `/${sitemapPath}`
  }`;
  lines.push(`Sitemap: ${sitemapAbsolute}`);

  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trim()}\n`;
}

function resolveAllowed(setting: "all" | "none" | readonly string[]): Set<string> {
  if (setting === "all") return new Set(AI_CRAWLERS.map((c) => c.userAgent));
  if (setting === "none") return new Set();
  return new Set(setting);
}
